### ISSUE TITLE
Work on turboeverdrive aliexpress?

### ISSUE THREAD

**Issue by jackygoule** [jbrandwood/teos#10]
Hello can i test on turboeverdrive aliexpress ?
Thanks

**Comment by jbrandwood** [comment]
If you want to try it, follow the instructions in the README.

But I wouldn't expect it to work, because I believe that the Chinese copies of Krikzz's Turbo Everdrive sold on aliexpress are copies of Krikzz's old version 1 hardware (based on flash-ROM), and TEOS requires Krikzz's version 2 hardware (based on RAM).

Krikzz does a LOT of work to create and support these Everdrive products, and as a small businessman trying to bring cool hardware to game players, I urge you to consider supporting him by buying his products directly from him, and not by buying the cheaper (and outdated) clones of his products from aliexpress.
