### ISSUE TITLE
[Feature Request] Listen to Pin 36 and react to hard reset

### ISSUE THREAD

**Issue by ArcadeTV** [jbrandwood/teos#9]
I've created a modding-pcb for adding an InGameReset to the PC Engine. The initial idea was being able to trigger a hard reset and go back to the TurboED menu without the need of hitting the reset button on the cart itself. After tinkering with a mcu and checking for a certain button-combo being held I pulled the /RESET line LOW and it worked as expected, but only the game resetted.
So, I'd like to request this feature: Check the status of pin 36 on the cart slot which is connected to the fpga and go back to the menu when it's LOW. 
I know the PC Engine never had a dedicated reset button but since the /RESET line is present and working I think it's legit for a flash-cart to be aware of this and react to it.
Thank You very much!

**Comment by dshadoff** [comment]
What you are asking is not possible from the TEOS level - this is the code executed by the PC Engine when it's "mapped in" to scope.  TEOS does not include any FPGA configuration/programming.

What you're asking would require the following, so I'm not sure whether it's even possible on the existing cards (because they were not designed to deal with this situation):

Access to the FPGA's programming code (which is closed-source).  Only Krikzz has this.  Tracing the wire leading from pin 36 on the HuCard port (on the v2.5 card) leads to a resistor, whose other side leads to pin 71 of the FPGA.  This is undoubtedly currently coded to be an OUTPUT, so that the Turbo Everdrive can reset the host machine.

While it may be possible to change this to become an input, there is no level-shift circuitry so the FPGA input (in order to sense a reset condition)) may not deal well with the 5V normally on this line.  The current design probably tri-states the line until it's required to be driven low.

On the bright side, Krikzz is currently in the process of designing a new version which will simulate the CDROM hardware as well, and has promised to make the BIOS and FPGA code available for open-source updates.  If you leave a message on the krikzz support board requesting /RESET to be monitorable, he may incorporate that into his design.

The support forum board is here:
https://krikzz.com/forum/index.php?board=13.0

**Comment by ArcadeTV** [comment]
I understand. Thank you very much for taking the time, it's very much appreciated!
